'use client'
import "./globals.css";
import { Provider } from "react-redux";
import { store } from '@/app/redux/store'


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

import { Navbar } from "@/components/navbar";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased min-h-screen">
        <Provider store={store}>
          <Navbar />
          <main className="min-h-[calc(100vh-64px)] overflow-x-hidden">
            {children}
          </main>
        </Provider>
      </body>
    </html>
  );
}
